name: NoblePaper
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14688
title: Noble Paper Graphic Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70099455-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dde168'
    - '#0b3549'
    - '#000000'
    - '#3c5d6d'
    - '#a8b7be'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
