name: NoblePaper
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36094737029634416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70099455-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0dfc1'
    - '#524949'
    - '#feef02'
    - '#71a090'
    - '#030202'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.7857378378976136
purpose: []
